[theme]
base = "dark"
primaryColor = "#0EA5E9"
backgroundColor = "#050F0B"
secondaryBackgroundColor = "#0C2B1D"
textColor = "#E3E8F7"
dataframeHeaderBackgroundColor = "#0F2318"
dataframeBorderColor = "rgba(255,255,255,0.10)"
